#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

spawn vm H1 network 1,2
spawn vm SW network 1,2,3,4
spawn vm H2 network 3,4

run

case $uts in
    H*)
        ip link set down dev eth0
        ip link set down dev eth1
        ethtool -s eth0 speed 1000 duplex full
        ethtool -s eth1 speed 1000 duplex full
        modprobe bonding
        ip link add name bond0 type bond mode 802.3ad miimon 100 lacp_rate fast
        ip link set dev eth0 master bond0
        ip link set dev eth1 master bond0
        ip link set up dev bond0
        ip link set up dev eth0
        ip link set up dev eth1
        ;;
    SW)
        ip link add name br0 type bridge stp_state 0 # group_fwd_mask 4
        ip link add name br1 type bridge stp_state 0 # group_fwd_mask 4
        ip link set dev eth0 master br0
        ip link set dev eth1 master br1
        ip link set dev eth2 master br0
        ip link set dev eth3 master br1
        ip link set dev eth0 type bridge_slave group_fwd_mask 4
        ip link set dev eth1 type bridge_slave group_fwd_mask 4
        ip link set dev eth2 type bridge_slave group_fwd_mask 4
        ip link set dev eth3 type bridge_slave group_fwd_mask 4
        ip link set up dev br0
        ip link set up dev br1
        ;;
esac

# H2$ ping fe80::5254:33ff:fe00:1 -I bond0 -c 3
# ping: Warning: source address might be selected on device other than: bond0
# PING fe80::5254:33ff:fe00:1(fe80::5254:33ff:fe00:1) from :: bond0: 56 data bytes
# 64 bytes from fe80::5254:33ff:fe00:1%bond0: icmp_seq=1 ttl=64 time=0.370 ms
# 64 bytes from fe80::5254:33ff:fe00:1%bond0: icmp_seq=2 ttl=64 time=1.92 ms
# 64 bytes from fe80::5254:33ff:fe00:1%bond0: icmp_seq=3 ttl=64 time=1.91 ms
#
# --- fe80::5254:33ff:fe00:1 ping statistics ---
# 3 packets transmitted, 3 received, 0% packet loss, time 2003ms
# rtt min/avg/max/mdev = 0.370/1.399/1.921/0.727 ms
