#!/bin/sh

LABNAME="vmx"

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

MEM=2G spawn vm U1 network 1
MEM=2G spawn vm U2 network 2
spawn juniper-vmx vMX1 networks 1,3
spawn juniper-vmx vMX2 networks 2,3

run

# Executed on each VM
case $uts in
    U1) ip addr add 192.0.2.0/31 dev eth0 ;;
    U2) ip addr add 192.0.2.2/31 dev eth0 ;;
esac

service gobgp
sleep 1
gobgp global rib add 0.0.0.0/0 -a ipv4
# We want the routers to have a slight difference in routes
skip=$(od -An -N1 -t u1 /dev/urandom)
# But this seems to trigger a bug in import (failed to parse: unsupported type: 16387)
skip=0
echo "
gobgp mrt inject global \
      --queue-size 128 \
      <(zcat /mnt/lab/latest-bview.gz) \
      10000 $skip
"

# Local Variables:
# mode: sh
# indent-tabs-mode: nil
# sh-basic-offset: 4
# End:
