#!/bin/sh

LABNAME="vmx"

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

MEM=512M spawn vm U1 network 1
MEM=512M spawn vm U2 network 2
spawn juniper-vmx vMX1 networks 1,3
spawn juniper-vmx vMX2 networks 2,3

run

# Executed on each VM
case $uts in
    U1)
        ip addr add 192.0.2.0/31 dev eth0
        template exabgp.conf exabgp.$uts.conf localip="'192.0.2.0'" peerip="'192.0.2.1'" localas=65001 peeras=64512 firstas=328474 max=10000
        ;;
    U2)
        ip addr add 192.0.2.2/31 dev eth0
        template exabgp.conf exabgp.$uts.conf localip="'192.0.2.2'" peerip="'192.0.2.3'" localas=65002 peeras=64512 firstas=206313 max=10000
        ;;
esac

export exabgp_log_destination=syslog
export exabgp_api_cli=false
export exabgp_api_ack=false
export exabgp_daemon_daemonize=true # only work if parent is not PID 1
(service exabgp exabgp.$uts.conf)

# Local Variables:
# mode: sh
# indent-tabs-mode: nil
# sh-basic-offset: 4
# End:
