#!/bin/sh

LABNAME="ecmp-vxlan"

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

# Which VM to spawn
vms=3
for i in $(seq 1 $vms); do
    spawn vm H$i networks $i,$((i+vms))
done
spawn vm bridges networks $(seq -s, 1 $((vms*2)))

run

# Executed on each VM
case $uts in
    bridges*)
        for br in br1 br2; do
            brctl addbr $br
            brctl stp $br off
            ip link set up dev $br
        done
        for i in $(seq 1 $vms); do
            brctl addif br1 eth$((i-1))
            brctl addif br2 eth$((vms+i-1))
        done
        ;;
    H*)
        sysctl -qw net.ipv4.ip_forward=1
        sysctl -qw net.ipv4.icmp_echo_ignore_broadcasts=0

        ip addr add 192.0.2.${uts#H}/25 dev eth0
        ip addr add 192.0.2.$((128 + ${uts#H}))/25 dev eth1

        ip addr add 203.0.113.${uts#H}/32 dev lo label lo:1
        ip link set multicast on dev lo
        service bird
        service pimd -N -c /mnt/lab/pimd.conf

        for i in $(seq 0 5); do
            ip link add vx$i type vxlan \
               dstport 4789 \
               id $((100 + i)) \
               ttl 5 \
               group 239.0.0.$((100 + i)) \
               dev lo \
               local 203.0.113.${uts#H}
            ip link set up dev vx$i
            ip addr add 192.168.${i}.${uts#H}/24 dev vx$i
        done
        ;;
esac
service nginx
service lldpd -I '*,!vx*'
