#!/bin/sh

LABNAME="trie-routes"

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

# Which VM to spawn
#MEM=512M spawn vm R1 # Lots of /32
MEM=512M spawn vm R2 # Partial view

run

sysctl -qw net.ipv4.ip_forward=1

# Set some output interfaces
for i in $(seq 1 5); do
    ip link add name out$i type dummy
    ip link set up dev out$i
    ip addr add 203.0.113.$((i*2))/31 dev out$i
done

# Add one path with reduced MTU
ip link add name out6 type veth peer name in6
ip link add name out7 type veth peer name in7
ip link set mtu 1400 dev out7
ip link set mtu 1400 dev in7
ip netns add next-hop
ip netns add next-next-hop
ip link set netns next-hop dev in6
ip link set netns next-hop dev out7
ip link set netns next-next-hop dev in7
ip link set up dev out6
ip addr add 203.0.113.12/31 dev out6
ip netns exec next-hop ip link set up dev in6
ip netns exec next-hop ip link set up dev out7
ip netns exec next-hop ip addr add 203.0.113.13/31 dev in6
ip netns exec next-hop ip addr add 203.0.113.14/31 dev out7
ip netns exec next-hop ip route add default via 203.0.113.15
ip netns exec next-next-hop ip link set up dev in7
ip netns exec next-next-hop ip addr add 203.0.113.15/31 dev in7
ip netns exec next-next-hop ip route add default via 203.0.113.14
ip route add 203.0.113.15 via 203.0.113.12

case $uts in
    R1)
        # Benchmark many /32
        mkdir -p stats/32
        for routes in 100 1000 10000 50000 100000 200000 500000 1000000 2000000; do
            for density in 1 0.5 0.1 0.05 0.01 0.001 0.0005; do
                ip route flush scope global
                sleep 1
                /usr/bin/time --verbose -o stats/32/time.$routes-$density \
                  ./many-32 -n $routes --density $density --batch 1000 \
                     203.0.113.3 203.0.113.5  203.0.113.7 \
                     203.0.113.9 203.0.113.11 203.0.113.13
                cat /proc/net/fib_triestat > stats/32/stat.$routes-$density
            done
        done
        ;;
    R2)
        # Router with a partial full view.
        ./from-bgp -n 1000000 --batch 1000 \
          203.0.113.3 203.0.113.5  203.0.113.7 \
          203.0.113.9 203.0.113.11 203.0.113.13
        ;;
esac
