#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

# Which VM to spawn
spawn vm R1 network 1
spawn vm R2 network 1
spawn juniper-vjunos vJunos network 1

run

# Executed on each VM
case $uts in
    R*)
        ip addr add 192.0.2.${uts#R}/24 dev eth0
        ip addr add 198.51.100.10${uts#R}/32 dev dummy0
        template bird.Rx.conf bird.$uts.conf index=${uts#R}
        service bird
        ;;
esac
