#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

# 2 = QFX1 to H1
# 3 = QFX2 to H1
# 4 = internal net
# 6 = Cumulus to H2
# 7 = Cumulus to H2

spawn juniper-vqfx QFX1 networks 2,4
#spawn juniper-vqfx QFX2 networks 3,4
spawn cumulus-vx CN networks 6,7,4
spawn vm H1 networks 2,3
spawn vm H2 networks 6,7

run

case $uts in
    H*)
        ip link add name lag1 type bond
        ip link set down dev eth0
        ip link set down dev eth1
        case $uts in
            H2)
                ethtool -s eth0 speed 1000 duplex full
                ethtool -s eth1 speed 1000 duplex full
                ;;
            H1)
                ethtool -s eth0 speed 10000 duplex full
                ethtool -s eth1 speed 10000 duplex full
                ;;
        esac
        >/sys/class/net/lag1/bonding/mode      echo 802.3ad
        >/sys/class/net/lag1/bonding/lacp_rate echo fast
        >/sys/class/net/lag1/bonding/miimon    echo 100
        >/sys/class/net/lag1/bonding/min_links echo 1
        >/sys/class/net/lag1/bonding/xmit_hash_policy echo layer3+4
        >/sys/class/net/lag1/bonding/slaves    echo +eth1
        >/sys/class/net/lag1/bonding/slaves    echo +eth0
        ip link set up dev lag1
        ip link set up dev eth0
        ip link set up dev eth1

        ip link add name lag1.654 link lag1 type vlan id 654
        ip link add name lag1.655 link lag1 type vlan id 655
        ip link set up dev lag1.654
        ip link set up dev lag1.655

        ip addr add 192.168.1.${uts#H}/24 dev lag1.654
        ip addr add 192.168.2.${uts#H}/24 dev lag1.655
        ;;
esac
