#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

# Which VM to spawn
spawn vm K1 network 1
spawn vm K2 network 2
spawn vm R1 network 1,2

run

# Executed on each VM
case $uts in
    R1)
        ip addr add 203.0.113.1/25 dev eth0
        ip addr add 203.0.113.129/25 dev eth1
        ip addr add 2001:db8:1::1/64 dev eth0
        ip addr add 2001:db8:2::1/64 dev eth1
        sysctl -qw net/ipv4/ip_forward=1
        sysctl -qw net.ipv6.conf.all.forwarding=1
        ;;
    K1)
        ip addr add 203.0.113.10/25 dev eth0
        ip route add default via 203.0.113.1
        ip addr add 2001:db8:1::10/64 dev eth0
        ip -6 route add default via 2001:db8:1::1
        keepalived -P -f $PWD/keepalived.$uts.conf
        ;;
    K2)
        ip addr add 203.0.113.140/25 dev eth0
        ip route add default via 203.0.113.129
        ip addr add 2001:db8:2::10/64 dev eth0
        ip -6 route add default via 2001:db8:2::1
        keepalived -P -f $PWD/keepalived.$uts.conf
        ;;
esac
