#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

spawn vm ping networks 1,2,3,4

spawn cumulus-vx  cumulus1 networks 1,5
spawn cumulus-vx  cumulus2 networks 2,6
spawn vm          bird1    networks 3,7
spawn juniper-vmx vmx1     networks 4,8

spawn cumulus-vx spine networks 5,6,7,8

case $uts in
    ping)
        for iface in /sys/class/net/eth*; do
            iface=${iface##*/}
            digit=${iface#eth}
            digit=$((digit*4 + 2))
            ip netns add $iface
            ip link set netns $iface $iface
            ip -n $iface link set up dev $iface
            ip -n $iface addr add 192.0.2.${digit}/30 dev $iface
            ip -n $iface route add default via 192.0.2.$((digit-1))
        done
        ;;
    bird1)
        sysctl -qw net.ipv4.ip_forward=1
        ip addr add 192.0.2.9/30 dev eth0
        ip addr add fc00::1:2/126 dev eth1
        service bird
esac

run
