#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

# Which VM to spawn
spawn vm R1 network 1
spawn vm R2 network 1

run

# Executed on each VM
case $uts in
    R*)
        ip addr add 2001:db8:1::1${uts#R}/64 dev eth0
        ip addr add 203.0.113.1${uts#R}/32 dev dummy0
        ip route add 203.0.113.1$(( 3-${uts#R} )) via inet6 2001:db8:1::1$(( 3-${uts#R} ))
        ;;
esac
service nginx
