#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

spawn vm ping networks 1,2
spawn cumulus-vx cumulus1 networks 1,3
spawn cumulus-vx cumulus2 networks 2,4

spawn cumulus-vx spine networks 3,4


case $uts in
    ping)
        for iface in /sys/class/net/eth*; do
            iface=${iface##*/}
            digit=${iface#eth}
            digit=$((digit*4 + 2))
            ip netns add $iface
            ip link set netns $iface $iface
            ip -n $iface link set up dev $iface
            ip -n $iface addr add 192.0.2.${digit}/30 dev $iface
            ip -n $iface route add default via 192.0.2.$((digit-1))
        done
        ;;
esac

run
