#!/bin/sh

# https://xrdocs.io/ncs5500/tutorials/bgp-evpn-configuration-ncs-5500-part-1/

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

if onhost; then
    while read hostname loopback ifaces isisnet prefixsid; do
        template cisco-XXX.conf cisco-${hostname}.conf \
                 loopback="'${loopback}'" \
                 ifaces=${ifaces} \
                 isisnet="'${isisnet}'" \
                 prefixsid=${prefixsid}
    done <<EOF
spine1 6.6.6.6 3 49.0001.0000.0000.0006.0 16006
spine2 7.7.7.7 3 49.0001.0000.0000.0007.0 16007
leaf1 1.1.1.1 2 49.0001.0000.0000.0001.0 16001
leaf2 2.2.2.2 2 49.0001.0000.0000.0002.0 16002
leaf5 5.5.5.5 2 49.0001.0000.0000.0005.0 16005
EOF
fi

spawn cisco-iosxrv spine1 network 16,26,56
spawn cisco-iosxrv spine2 network 17,27,57
spawn cisco-iosxrv leaf1 network 16,17,1
spawn cisco-iosxrv leaf2 network 26,27,2
spawn cisco-iosxrv leaf5 network 56,57,5
spawn vm H1 network 1,2
spawn vm H5 network 5

run

case $uts in
    H1)
        ip link set down dev eth0
        ip link set down dev eth1
        ethtool -s eth0 speed 1000 duplex full
        ethtool -s eth1 speed 1000 duplex full
        modprobe bonding
        ip link add name bond0 type bond mode 802.3ad miimon 100 lacp_rate fast
        ip link set dev eth0 master bond0
        ip link set dev eth1 master bond0
        ip link set up dev bond0
        ip link set up dev eth0
        ip link set up dev eth1
        ip addr add 10.0.0.10/24 dev bond0
        ;;
    R2)
        ip addr add 10.0.0.50/24 dev eth0
        ;;
esac
