#!/bin/sh

[ -d /sys/kernel/kbench ] && rmmod kbench_mod
[ -d /sys/kernel/kbench ] || insmod ./kbench_mod.ko
mkdir -p stats/many-128
for routes in 10000 20000 30000 40000 50000 100000 200000 500000 1000000 2000000; do
    ip -6 route flush proto static
    sleep 1
    echo "routes: $routes"
    /usr/bin/time --verbose -o stats/many-128/time.$routes \
                  ./insert-many-128 -n $routes --batch 500 \
                  2001:db8:1::3 2001:db8:1::5  2001:db8:1::7 \
                  2001:db8:1::9 2001:db8:1::11 2001:db8:1::13
    cat /proc/net/rt6_stats > stats/many-128/stat.$routes
    sed -ne 1,2p -e '/^ip6/p' -e '/^fib6/p' /proc/slabinfo > stats/many-128/slab.$routes
    [ -d /sys/kernel/kbench ] && {
        # The space is a bit too wide to be able to cover it properly, let's restrict a bit
        echo 2001:db8:b:0:5254:ff:fe00:: > /sys/kernel/kbench/flow_dst_ipaddr_s
        echo 2001:db8:b:0:5254:ff:ff00:: > /sys/kernel/kbench/flow_dst_ipaddr_e
        cat /sys/kernel/kbench/run_verbose > stats/many-128/kbench.$routes
    }
done
