#!/bin/sh

# Execute benchmark for all kernels.

set -ex

ESC="$(printf '\033')"
TREE=$1
shift

for version in $(git --git-dir="$TREE"/.git tag \
                     -l --sort='-taggerdate' --format='%(taggerdate:short) %(refname:lstrip=2)' \
                     v3\* v4\* \
    | awk '{print $2}' \
    | grep '^v[2-9][0-9.]*$' \
    | sort -Vr \
    | awk -F'.' '($2!=last) {last=$2;print}'); do
    version=${version#v}
    (cd "$TREE" ; git checkout v$version
     case $version in
         4.15.*)
             git cherry-pick 4b0110291ae1d618384cab105b1e2d208a31a6e3
             git cherry-pick ad343a98e74e85aa91d844310e797f96fee6983b
             ;;
         4.13.*|4.12.*|4.11.*|4.10.*)
             git cherry-pick cd696744d6d71fbb8b5f2728b25afb51cc3811d7
             git cherry-pick 941bfd125c78713649eefb338e52300585fd6ec7
             git cherry-pick faf470583a5701c286c62f0dfaaa06964a8c4ed8
             ;;
         4.8.*)
             git cherry-pick cd696744d6d71fbb8b5f2728b25afb51cc3811d7
             git cherry-pick 941bfd125c78713649eefb338e52300585fd6ec7
             git cherry-pick faf470583a5701c286c62f0dfaaa06964a8c4ed8
             git cherry-pick 85f687708c81
             git cherry-pick 8de6ea44af5c
             ;;
         4.7.*|4.6.*|4.5.*|4.3.*|4.2.*)
             git cherry-pick cd696744d6d71fbb8b5f2728b25afb51cc3811d7
             git cherry-pick 941bfd125c78713649eefb338e52300585fd6ec7
             git cherry-pick faf470583a5701c286c62f0dfaaa06964a8c4ed8
             git cherry-pick 85f687708c81
             git cherry-pick 8de6ea44af5c
             git cherry-pick -Xtheirs 1c7727d0bca0c620850834d8e4913a1f5bdc6cb7
             git cherry-pick 56df604296c2
             ;;
         4.0.*) git cherry-pick 99124e4db5b7 ;;
         3.9.*) git cherry-pick 4800af91229e ;;
         3.11.*) git cherry-pick e4037eb7c531 ;;
         3.13.*) git cherry-pick 510458cb7da6 ;;
         3.15.*) git cherry-pick dd727f0191ea ;;
         3.17.*) git cherry-pick b28283637b3b ;;
         3.19.*) git cherry-pick 99124e4db5b7 ;;
         2.6.39|3.[1356].*) git cherry-pick 83b53b8cc693 ;;
     esac)
    case $version in
        3.[02489].*)
            (cd "$TREE"; git am) < 0001-netlink-ignore-unknown-attributes.patch
            ;;
        3.[567].*)
            (cd "$TREE"; git am) < 0001-netlink-ignore-unknown-attributes-2.patch
            ;;
        2.6.39|3.[13].*)
            (cd "$TREE"; git am) < 0001-netlink-ignore-unknown-attributes-3.patch
            ;;
    esac
    VERSION=$(make --no-print-directory -C "$TREE" kernelversion)
    [ ! -f stats/kernel/$VERSION ] || continue
    printf "\033]1;$version\007"
    printf "\033]2;$version\007"
    printf "\033k$version\033\\"
    ./bench-kernel "$TREE" "$@" || true
    [ -f ./stats/kernel/$VERSION ] || break
done
