#!/bin/sh

# Execute benchmark for all kernels. This is not very reliable as if
# the latest kernel is not a stable release, it doesn't work.

set -e

ESC="$(printf '\033')"
TREE=$1
shift

git --git-dir="$TREE"/.git tag \
    | grep '^v[34][0-9.]*$' \
    | sort -Vr \
    | awk 'BEGIN { prefix="NOTHING" }
           (substr($0, 0, length(prefix)) == prefix) { next }
           { print ; sub(/\.[0-9]+$/, "") ; prefix=$0 }' \
               | while read version; do
    version=${version#v}
    (cd $1 ; git checkout v$version)
    rm stats/kernel/$version
    printf "\033]1;$version\007"
    printf "\033]2;$version\007"
    printf "\033k$version\033\\"
    ./bench-kernel "$TREE" "$@" || true
    [ -f ./stats/kernel/$version ]
done
