#!/bin/sh

[ -d /sys/kernel/kbench ] && rmmod kbench_mod
[ -d /sys/kernel/kbench ] || insmod ./kbench_mod.ko
mkdir -p stats/full
for routes in 0 100 500 1000 2000 5000 10000 20000 30000 40000; do
    ip -6 route flush proto static
    sleep 1
    echo "routes: $routes"
    /usr/bin/time --verbose -o stats/full/time.$routes \
                  ./insert-from-bgp -n $routes --batch 500 \
                  2001:db8:1::3 2001:db8:1::5  2001:db8:1::7 \
                  2001:db8:1::9 2001:db8:1::11 2001:db8:1::13
    [ $routes -eq 0 ] && ip -6 route add 2000::/3 via 2001:db8:1::3 proto static 2> /dev/null
    cat /proc/net/rt6_stats > stats/full/stat.$routes
    sed -ne 1,2p -e '/^ip6/p' -e '/^fib6/p' /proc/slabinfo > stats/full/slab.$routes
    [ -d /sys/kernel/kbench ] && {
        # The space is a bit too wide to be able to cover it properly, let's restrict a bit
        echo 2a00:: > /sys/kernel/kbench/flow_dst_ipaddr_s
        echo 2a04:: > /sys/kernel/kbench/flow_dst_ipaddr_e
        cat /sys/kernel/kbench/run_verbose > stats/full/kbench.$routes
    }
done
