#!/bin/sh

[ -d /sys/kernel/kbench ] && rmmod kbench_mod
[ -d /sys/kernel/kbench ] || insmod ./kbench_mod.ko
mkdir -p stats/many-48
for routes in 0 100 500 1000 2000 5000 10000 20000 30000 40000 50000 100000 200000 500000 1000000 2000000; do
    for density in 1 0.5 0.1 0.05 0.01 0.001; do
        ip -6 route flush proto static
        sleep 1
        echo "routes: $routes — density: $density"
        /usr/bin/time --verbose -o stats/many-48/time.$routes-$density \
                      ./insert-many-48 -n $routes --batch 500 --density $density \
                      2001:db8:1::3 2001:db8:1::5  2001:db8:1::7 \
                      2001:db8:1::9 2001:db8:1::11 2001:db8:1::13
        ip -6 route add 2001:db8::/32 via 2001:db8:1::3 proto static 2> /dev/null
        cat /proc/net/rt6_stats > stats/many-48/stat.$routes-$density
        sed -ne 1,2p -e '/^ip6/p' -e '/^fib6/p' /proc/slabinfo > stats/many-48/slab.$routes-$density
        [ -d /sys/kernel/kbench ] && {
            echo 2001:db8:c:: > /sys/kernel/kbench/flow_dst_ipaddr_s
            echo 2001:db8:c350:: > /sys/kernel/kbench/flow_dst_ipaddr_e
            echo 100000 > /sys/kernel/kbench/loop_count
            cat /sys/kernel/kbench/run_verbose > stats/many-48/kbench.$routes-$density
        }
    done
done
