#!/bin/sh

LABNAME="vxlan"

# Choose one variant:
#VARIANT=multicast
#VARIANT=unicast-static-default
VARIANT=unicast-static-l2

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

# Network 1 is the underlay network. We consider it as a routed L3
# network, but we lie a bit.
spawn vm S1 networks 1,2
spawn vm S2 networks 1,3,4
spawn vm S3 networks 1,5

spawn vm H1 network 2
spawn vm H2 network 3
spawn vm H3 network 4
spawn vm H4 network 5

run

noip() {
    # Linux have IP enabled on all interfaces and it cannot be
    # disabled for IPv4. Let's use iptables when we want to disable IP
    # processing on an interface. ARP requests will still be
    # processed. Don't try to be too smart, the goal is just to avoid
    # the switches to answer to some multicast traffic.
    iptables -I INPUT -i $1 -j DROP
    ip6tables -I INPUT -i $1 -j DROP
}

# Executed on each VM
case $uts in
    H*)
        ip -6 addr add 2001:db8:ff::$(( ${uts#H} + 9 ))/64 dev eth0
        service nginx
        ;;
    S*)
        # Setup the "routed" underlay network
        # On lo, an IPv6 loopback address would be marked as
        # "unreachable" (and not considered by BIRD). Therefore, we put it on dummy0.
        ip -6 addr add 2001:db8:${uts#S}::1/128 dev dummy0
        service bird

        brctl addbr br0
        brctl setfd br0 0
        for iface in /sys/class/net/eth*; do
            [ -d $iface ] || continue
            iface=${iface##*/}
            case $iface in
                eth0) ;;
                *)
                    brctl addif br0 $iface
                    noip $iface
                    ;;
            esac
        done

        case $VARIANT in
            multicast)
                # VXLAN configuration using multicast
                ip link add vxlan0 type vxlan \
                   dstport 4789 \
                   id 100 \
                   ttl 5 \
                   group ff05::100 \
                   dev eth0 \
                   local 2001:db8:${uts#S}::1
                ;;
            unicast-static-default)
                # VXLAN configuration using unicast flooding.
                ip -6 link add vxlan0 type vxlan \
                   dstport 4789 \
                   id 100 \
                   ttl 5 \
                   local 2001:db8:${uts#S}::1
                ;;
            unicast-static-l2)
                # Same as previously, but we disable learning as we
                # don't expect any additional entries (this could
                # protect us from some exhaustion attack).
                ip -6 link add vxlan0 type vxlan \
                   dstport 4789 \
                   id 100 \
                   ttl 5 \
                   local 2001:db8:${uts#S}::1 \
                   nolearning
                ;;
        esac
        case $VARIANT in
            unicast-static-default|unicast-static-l2)
                # Any BUM frame will be sent to the other hosts. We
                # need that even for static L2 as we will have
                # broadcast/multicast frames for neighbors discovery
                # (ARP/ND). Not strictly needed for unicast static L3
                # case (but no broadcast will be possible then).
                [ ${uts#S} = 1 ] || bridge fdb append 00:00:00:00:00:00 dev vxlan0 dst 2001:db8:1::1
                [ ${uts#S} = 2 ] || bridge fdb append 00:00:00:00:00:00 dev vxlan0 dst 2001:db8:2::1
                [ ${uts#S} = 3 ] || bridge fdb append 00:00:00:00:00:00 dev vxlan0 dst 2001:db8:3::1
        esac
        case $VARIANT in
            unicast-static-l2)
                # We put static entries for known mac.
                [ ${uts#S} = 1 ] || bridge fdb append 50:54:33:00:00:08 dev vxlan0 dst 2001:db8:1::1
                [ ${uts#S} = 2 ] || bridge fdb append 50:54:33:00:00:09 dev vxlan0 dst 2001:db8:2::1
                [ ${uts#S} = 2 ] || bridge fdb append 50:54:33:00:00:0a dev vxlan0 dst 2001:db8:2::1
                [ ${uts#S} = 3 ] || bridge fdb append 50:54:33:00:00:0b dev vxlan0 dst 2001:db8:3::1
                ;;
        esac

        noip vxlan0
        noip br0
        brctl addif br0 vxlan0
        ip link set up dev vxlan0
        ip link set up dev br0
        ;;
esac
