#!/bin/sh

LABNAME="vmx"

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

# Which VM to spawn
spawn vm R1 network 1
spawn vm R2 network 1
spawn juniper-vmx vMX network 1

run

# Executed on each VM
case $uts in
    R1)
        ip addr add 192.0.2.1/24 dev eth0
        ip addr add 198.51.100.101/32 dev dummy0
        service bird
        ;;
    R2)
        ip addr add 192.0.2.2/24 dev eth0
        ip addr add 198.51.100.102/32 dev dummy0
        service bird
        ;;
esac

# Local Variables:
# mode: sh
# indent-tabs-mode: nil
# sh-basic-offset: 4
# End:
