#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

spawn vm injector network 1
spawn vm internet network 2
spawn vm customer network 3
spawn cisco-iosxrv xrv1 network 1,2,3

run

case $uts in
    injector)
        ip addr add 192.0.2.20/31 dev eth0
        service bird
        ;;
    internet)
        ip addr add 192.0.2.10/31 dev eth0
        ip route add default via 192.0.2.11
        ip addr add 8.8.8.8/32 dev dummy0
        ip addr add 1.1.1.1/32 dev dummy0
        ;;
    customer)
        ip addr add 203.0.113.15/24 dev eth0
        ip route add default via 203.0.113.254
        ;;
esac
