#!/bin/sh

[ -d /sys/kernel/kbench ] && rmmod kbench_mod
[ -d /sys/kernel/kbench ] || insmod ./kbench_mod.ko
mkdir -p stats/iprules

ip route flush scope global
./insert-from-bgp -n 100000 --batch 1000 \
           203.0.113.3 203.0.113.5  203.0.113.7 \
           203.0.113.9 203.0.113.11 203.0.113.13

ip route add blackhole default table 142

current=0
for rules in 0 1 2 3 5 6 7 8 9 10 20 30 40 50 60 80 90 100 200 300 400 500 800 1000; do
    while [ $current -lt $rules ]; do
        current=$((current + 1))
        ip rule add iif vlan$current table 142
    done
    [ -d /sys/kernel/kbench ] && {
        echo 50000 > /sys/kernel/kbench/loop_count
        cat /sys/kernel/kbench/run > stats/iprules/kbench.$rules
    }
done
