#!/bin/sh

LABNAME="redundant-vpn"
DEPENDENCIES="racoon ospfd bgpd setkey"

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

spawn vm R1 network 1
spawn vm R2 network 2
spawn vm V1 networks 1,5
spawn vm V2 networks 1,5
spawn vm V3 networks 2,5
spawn vm V4 networks 2,5
spawn vm I1 network 5

run

setup_racoon() {
    rm -f /etc/racoon/racoon.conf
    ln -s $PWD/$uts/racoon/racoon.conf /etc/racoon/.
    mkdir /var/run/racoon
    cp racoon-psk.txt /etc/racoon/psk.txt
    chmod 600 /etc/racoon/psk.txt
    chown root /etc/racoon/psk.txt
    log_begin_msg "Setup IPsec policies"
    local="$1" ; shift
    remote="$1" ; shift
    for net in "$@"; do
	net1=${net%-*}
	net2=${net#*-}
	cat <<EOF
spdadd $net2 $net1 any -P in ipsec
  esp/tunnel/${remote}-${local}/require;
spdadd $net1 $net2 any -P out ipsec
  esp/tunnel/${local}-${remote}/require;
EOF
    done | setkey -c
    log_ok_msg "IPsec policies configured"
    service racoon
}


sysctl -qw net.ipv4.ip_forward=1
case ${uts} in
    R1)
	modprobe dummy
	ip link set up dev dummy0
	ip addr add 192.168.15.1/24 dev dummy0
	ip addr add 192.168.1.10/24 dev eth0
	service quagga
	;;
    R2)
	modprobe dummy
	ip link set up dev dummy0
	ip addr add 192.168.115.1/24 dev dummy0
	ip addr add 192.168.101.10/24 dev eth0
	service quagga
	;;
    V1)
	ip addr add 192.168.1.11/24 dev eth0
	ip addr add 1.1.2.1/24 dev eth1
	ip route add default via 1.1.2.10
	service quagga
	setup_racoon 1.1.2.1 1.1.1.1 192.168.0.0/19-192.168.100.0/19
	;;
    V2)
	ip addr add 192.168.1.12/24 dev eth0
	ip addr add 1.1.2.2/24 dev eth1
	ip route add default via 1.1.2.10
	service quagga
	setup_racoon 1.1.2.2 1.1.1.2 192.168.0.0/19-192.168.100.0/19
	;;
    V3)
	ip addr add 192.168.101.13/24 dev eth0
	ip addr add 1.1.1.1/24 dev eth1
	ip route add default via 1.1.1.10
	service quagga
	setup_racoon 1.1.1.1 1.1.2.1 192.168.100.0/19-192.168.0.0/19
	;;
    V4)
	ip addr add 192.168.101.14/24 dev eth0
	ip addr add 1.1.1.2/24 dev eth1
	ip route add default via 1.1.1.10
	service quagga
	setup_racoon 1.1.1.2 1.1.2.2 192.168.100.0/19-192.168.0.0/19
	;;
    I1)
	ip addr add 1.1.1.10/24 dev eth0
	ip addr add 1.1.2.10/24 dev eth0
	;;
esac
