#!/bin/sh

LABNAME="bridge-linux"

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

# Which VM to spawn
spawn vm VM1 network 1
spawn vm VM2 network 2
spawn vm VM3 network 3
spawn vm H1 network 4,5,1,2,3   # Hypervisor
spawn vm ER1 network 4,6        # Edge public router
spawn vm IR2 network 5,6        # Internal router

run

# Executed on each VM
case $uts in
    VM*)
        ip addr add 192.0.2.1${uts#VM}/25 dev eth0
        ip -6 addr add 2001:db8:a::1${uts#VM}/64 dev eth0
        # Default to ER1
        ip route add default via 192.0.2.1
        ip -6 route add default via 2001:db8:a::1
        ;;
    H1)
        brctl addbr br0
        brctl addif br0 eth0    # "Internet"
        brctl addif br0 eth2    # VM1
        brctl addif br0 eth3    # VM2
        brctl addif br0 eth4    # VM3
        ip link set up dev br0
        ip addr add 192.168.14.3/24 dev eth1
        ip -6 addr add 2001:db8:b::3/64 dev eth1
        ip route add default via 192.168.14.1
        ip -6 route add default via 2001:db8:b::1
        ;;
    ER1)
        sysctl -qw net/ipv4/ip_forward=1
        sysctl -qw net/ipv6/conf/all/forwarding=1
        ip addr add 192.0.2.1/25 dev eth0
        ip addr add 2001:db8:a::1/64 dev eth0
        # Internet...
        ip addr add 203.0.113.10/24 dev eth1
        ;;
    IR2)
        sysctl -qw net/ipv4/ip_forward=1
        sysctl -qw net/ipv6/conf/all/forwarding=1
        ip addr add 192.168.14.1/24 dev eth0
        ip addr add 2001:db8:b::1/64 dev eth0
        iptables -t nat -I POSTROUTING -o eth1 -j MASQUERADE
        # Internet...
        ip addr add 203.0.113.11/24 dev eth1
        ip route add 192.0.2.0/25 via 203.0.113.10
        ;;
esac
