#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

spawn vm R1 network 1
spawn vm R2 network 1
spawn cisco-iosxrv IOS1 network 1

run

case $uts in
    R1)
        ip addr add 192.0.2.1/29 dev eth0
        ip addr add 203.0.113.1/32 dev dummy0
        ip addr add 203.0.113.10/32 dev dummy0
        ip addr add 203.0.113.11/32 dev dummy0
        service bird
        ;;
    R2)
        ip addr add 192.0.2.2/29 dev eth0
        ip addr add 203.0.113.2/32 dev dummy0
        service bird
        ;;
esac

# Once everything is established, on IOS:
# debug bgp nexthop

# On R1:
# ip route del 203.0.113.10/32
