#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

# Which VM to spawn
spawn vm C1 network  1
spawn vm V1 networks 1,2
spawn vm R1 networks 2,3
spawn vm V2 networks 4,3
spawn vm C2 network  4

run

case $uts in
    C1)
        ip addr add 172.16.1.10/24 dev eth0
        ip route add default via 172.16.1.1
        ;;
    V1)
        ip addr add 172.16.1.1/24 dev eth0
        ip link set mtu 1480 dev eth1
        ip addr add 203.0.113.10/29 dev eth1

        # Interface-based routing setup
        ip rule add iif lo table 100
        ip rule add iif eth1 table 100
        ip route add 172.16.1.0/24 dev eth0 table 100
        ip route add default via 203.0.113.11 table 100

        # VTI tunnel
        ip tunnel add vti0 mode vti local 203.0.113.10 remote 203.0.113.19 key 5
        ip link set up dev vti0
        ip addr add 169.254.15.0/31 dev vti0
        ip route add 172.17.1.0/24 via 169.254.15.1 dev vti0
        ;;
    R1)
        sysctl -qw net.ipv4.conf.all.forwarding=1
        ip link set mtu 1480 dev eth0
        ip addr add 203.0.113.11/29 dev eth0
        ip link set mtu 1460 dev eth1
        ip addr add 203.0.113.20/29 dev eth1
        ;;
    V2)
        ip link set mtu 1460 dev eth1
        ip addr add 203.0.113.19/29 dev eth1
        ip addr add 172.17.1.1/24 dev eth0
        ip route add default via 203.0.113.20

        # VTI tunnel
        ip tunnel add vti0 mode vti local 203.0.113.19 remote 203.0.113.10 key 5
        ip link set up dev vti0
        ip addr add 169.254.15.1/31 dev vti0
        ip route add 172.16.1.0/24 via 169.254.15.0
        ;;
    C2)
        ip addr add 172.17.1.10/24 dev eth0
        ip route add default via 172.17.1.1
        ;;
esac

case $uts in
    V*)
        sysctl -qw net.ipv4.conf.all.forwarding=1
        sysctl -qw net.ipv4.conf.vti0.disable_policy=1
        ip link set mtu 1500 dev vti0

        ln -sf $PWD/ipsec.secrets $PWD/ipsec.conf /etc/
        sed -i 's/\( *\)# install_routes =.*/\1 install_routes = no/' /etc/strongswan.d/charon.conf
        sed -i 's/\( *\)# install_virtual_ip =.*/\1 install_virtual_ip = no/' /etc/strongswan.d/charon.conf
        sed -i 's/\( *\)# routing_table =.*/\1 routing_table = 0/' /etc/strongswan.d/charon.conf
        service ipsec start
        ;;
    C*)
        service nginx
        ;;
esac
