#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

[ -f ssh_key_rtr ] || ssh-keygen -qN "" -t rsa -f ssh_key_rtr
[ -f ssh_key_r2 ]  || ssh-keygen -qN "" -t rsa -f ssh_key_r2
[ -f ssh_key_r3 ]  || ssh-keygen -qN "" -t rsa -f ssh_key_r3

spawn vm           R1  network 1
spawn vm           R2  networks 1,2         # BIRD+RPKI
spawn juniper-vrr  R3  networks 1,2         # JunOS+RPKI
spawn vm           RTR network 2

run

# Executed on each VM
case $uts in
    RTR)
        ip addr add 2001:db8:bbbb::f/124 dev eth0
        service nginx
        ln -s $PWD/rpki.json /tmp/nginx/www
        # Refresh is expected to happen on-demand by sending SIGHUP to gortr
        gortr -refresh=600 -verify=false -checktime=false \
              -cache=http://127.0.0.1/rpki.json \
              -ssh.bind=:8283 \
              -ssh.key=$PWD/ssh_key_rtr \
              -ssh.method.key=true \
              -ssh.auth.user=rpki \
              -ssh.auth.key.file=$PWD/ssh_key_r2.pub \
            &
        ;;
    R1)
        ip addr add 2001:db8:aaaa::f/124 dev eth0
        ip route add 2001:db8:cccc::/48 dev dummy0 table 10 # valid
        ip route add 2001:db8:dddd::/48 dev dummy0 table 10 # invalid
        ip route add 2001:db8:eeee::/48 dev dummy0 table 10 # unknown
        ip route add 2001:db8:ffff::/48 dev dummy0 table 10 # invalid
        service bird
        ;;
    R2)
        ip addr add 2001:db8:aaaa::1/124 dev eth0
        ip addr add 2001:db8:bbbb::1/124 dev eth1
        (echo -n "[2001:db8:bbbb::f]:8283 " ; cat ssh_key_rtr.pub) > /tmp/known_hosts
        service bird
        ;;
esac
