#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

spawn vm  R1  network 1
spawn vm  R2  networks 1,2         # BIRD+RPKI
spawn vm  RTR network 2

run

# Executed on each VM
case $uts in
    RTR)
        ip addr add 2001:db8:bbbb::0/126 dev eth0
        service nginx
        ln -s $PWD/rpki.json /tmp/nginx/www
        gortr -verify=false -checktime=false -cache=http://127.0.0.1/rpki.json &
        ;;
    R1)
        ip addr add 2001:db8:aaaa::0/126 dev eth0
        ip route add 2001:db8:cccc::/48 dev dummy0 table 10 # valid
        ip route add 2001:db8:dddd::/48 dev dummy0 table 10 # invalid
        service bird
        ;;
    R2)
        ip addr add 2001:db8:aaaa::1/126 dev eth0
        ip addr add 2001:db8:bbbb::1/126 dev eth1
        service bird
        ;;
esac
