#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

# Which VM to spawn
spawn vm private network 1
spawn vm public network 2
spawn vm mixed1 network 1,2
spawn vm mixed2 network 1,2

run

# Executed on each VM
case $uts in
    private)
        ip addr add 10.234.78.1/24 dev eth0
        ip addr add 2001:db8:ff::1/64 dev eth0
        ip addr add 192.168.1.1/32 dev lo
        ip addr add 2001:db8:cafe::1/128 dev lo
        ;;
    public)
        ip addr add 203.0.113.1/24 dev eth0
        ip addr add 2001:db8::1/64 dev eth0
        ip addr add 1.1.1.1/32 dev lo
        ip addr add 2606:4700:4700::1111/128 dev lo
        ;;
    mixed*)
        ifup --interfaces=$PWD/interfaces.$uts -a --no-scripts
        # Solution 1 for nginx with VRF:
        [ $uts != mixed2 ] || sysctl -w net.ipv4.tcp_l3mdev_accept=1
        ;;
esac
service nginx
