#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

spawn vm R1 network 1
spawn vm R2 network 1

run

# Executed on each VM
case $uts in
    R1)
        ip addr add 203.0.113.1/24 dev eth0
        ip link add type veth
        ip link set up dev veth0
        ip addr add 192.0.2.10/24 dev veth0
        ip route add 1.1.1.1/32 via 192.0.2.1
        sysctl -qw net.ipv4.conf.veth0.ignore_routes_with_linkdown=1
        ;;
    R2)
        ip addr add 203.0.113.2/24 dev eth0
        ;;
esac
template bird.Rx.conf bird.$uts.conf i=${uts#R}
service bird
