#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

# Which VM to spawn
spawn vm R1  networks 1,2
spawn vm R2  networks 1,3
spawn vm H1  network  2
spawn vm H2  network  3

# Choose one of the following lines:
#spawn vm RR1 network  1
spawn juniper-vrr RR1 networks 1

run

# Executed on each VM
case $uts in
    R1)
        ip addr add 192.0.2.1/24 dev eth0
        ip addr add 203.0.113.1/24 dev eth1
        sysctl -qw net/ipv4/ip_forward=1
        service bird
        ;;
    R2)
        ip addr add 192.0.2.2/24 dev eth0
        ip addr add 198.51.100.1/24 dev eth1
        sysctl -qw net/ipv4/ip_forward=1
        service bird
        ;;
    RR1)
        ip addr add 192.0.2.254/24 dev eth0
        service bird
        ;;
    H1)
        ip addr add 203.0.113.10/24 dev eth0
        ip route add default via 203.0.113.1
        ;;
    H2)
        ip addr add 198.51.100.10/24 dev eth0
        ip route add default via 198.51.100.1
        ;;
esac
service nginx
