#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

# Using the following topology:
#  https://github.com/CumulusNetworks/cldemo-roh-ansible

# Generate templates
if onhost; then
    for host in leaf01 leaf02 leaf03 leaf04 spine01 spine02; do
        rm -rf $host
        find cumulusX -type f | while read source; do
            target=$host/${source#*/}
            mkdir -p $(dirname $target)
            case $host in
                leaf*)
                    neighbors="swp1 swp2 swp3 swp4 swp5 swp6"
                    offset=10
                    number=${host#leaf}
                    ;;
                spine*)
                    neighbors="swp1 swp2 swp3 swp4"
                    offset=20
                    number=${host#spine}
                    ;;
            esac
            case $source in
                *.j2)
                    target=${target%.j2}
                    template $source $target \
                             loopback="'10.0.0.$((offset + number))'" \
                             asn=$((65000 + offset + number)) \
                             neighbors="'$neighbors'"
                    ;;
                *)
                    cp $source $target
                    grep -Fqx /$target .gitignore 2>/dev/null || echo /$target >> .gitignore
                    ;;
            esac
        done
    done
fi

# Which VM to spawn
spawn cumulus-vx leaf01 networks 1,3,9,10,13,14
spawn cumulus-vx leaf02 networks 2,4,9,10,15,16
spawn cumulus-vx leaf03 networks 5,7,11,12,17,18
spawn cumulus-vx leaf04 networks 6,8,11,12,19,20
spawn cumulus-vx spine01 networks 13,15,17,19
spawn cumulus-vx spine02 networks 14,16,18,20

spawn vm server01 networks oob,1,2
spawn vm server02 networks oob,3,4
spawn vm server03 networks oob,5,6
spawn vm server04 networks oob,7,8

run

# servers
sysctl -p sysctl.conf
ip addr add 10.0.0.$((30 + ${uts#server}))/32 dev lo
template cumulusX/etc/frr/frr.conf.j2 quagga-bgpd.$uts.conf \
                         loopback="'10.0.0.$((30 + ${uts#server}))'" \
                         asn=$((65100 + ${uts#server})) \
                         neighbors="'eth1 eth2'"
ln -sf quagga-bgpd.$uts.conf quagga-zebra.$uts.conf
service quagga
