#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

MEM=1G spawn img freebsd networks oob,1
MEM=1G spawn img freebsd-debug network oob
spawn vm linux network 1

run

# Linux
ip addr add 192.0.2.10/31 dev eth0
ip addr add 203.0.113.15/32 dev lo
service bird

service nginx
