#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

spawn vm R1 network 1,3,4
spawn vm R2 network 1,5,6
spawn vm H1 network 3
spawn vm H2 network 5
spawn vm H3 network 4
spawn vm H4 network 6

run

case $uts in
    R*)
        ip addr add 100.64.0.${uts#R}/28 dev eth0
        ip link add vx0 type vxlan local 100.64.0.${uts#R} dstport 4789 external vnifilter nolearning
        ip link add br0 type bridge vlan_filtering 1 vlan_stats_enabled 1 vlan_stats_per_port 1
        ip link set vx0 master br0
        ip link set vx0 type bridge_slave vlan_tunnel on
        ip link set br0 addr aa:bb:cc:00:00:0${uts#R}
        ip link set br0 up
        ip link set vx0 up
        sysctl -qw net.ipv4.conf.vx0.forwarding=1
        sysctl -qw net.ipv6.conf.vx0.forwarding=1

        # L3VNI
        while read vni vrf; do
            ip link add $vrf type vrf table $vni
            ip link set up $vrf
            ip link add name l3vni$vni link br0 type vlan id $vni protocol 802.1q
            bridge vlan add vid $vni dev br0 self
            ip link set l3vni$vni up
            ip link set l3vni$vni master $vrf
            bridge vni add dev vx0 vni $vni
            bridge vlan add dev vx0 vid $vni master
            bridge vlan add dev vx0 vid $vni tunnel_info id $vni master
            bridge vlan set dev vx0 vid $vni neigh_suppress on
            sysctl -qw net.ipv4.conf.l3vni$vni.forwarding=1
            sysctl -qw net.ipv6.conf.l3vni$vni.forwarding=1
        done <<EOF
100 vrf1
200 vrf2
EOF

        # vrf3
        ip link add vrf3 type vrf table 300
        ip link set up vrf3

        # L2VNI
        while read router iface vni vrf ip4 ip6; do
            [ $uts = $router ] || continue
            ip link add name l2vni$vni link br0 type vlan id $vni protocol 802.1q
            bridge vlan add vid $vni dev br0 self
            ip link set l2vni$vni up
            ip addr add $ip4 dev l2vni$vni
            ip addr add $ip6 dev l2vni$vni
            [ $vrf = _ ] || {
                ip link set l2vni$vni master $vrf
                sysctl -qw net.ipv4.conf.l2vni$vni.forwarding=1
                sysctl -qw net.ipv6.conf.l2vni$vni.forwarding=1
            }
            bridge vni add dev vx0 vni $vni
            bridge vlan add dev vx0 vid $vni master
            bridge vlan add dev vx0 vid $vni tunnel_info id $vni master
            bridge vlan set dev vx0 vid $vni neigh_suppress on

            ip link set $iface master br0
            ip link set $iface type bridge_slave neigh_vlan_suppress on
            bridge vlan add dev $iface vid $vni master pvid untagged
        done <<EOF
R1 eth1 110 vrf1 10.0.10.1/24 2001:db8:0:10::1/64
R2 eth1 220 vrf2 10.0.20.1/24 2001:db8:0:20::1/64
R1 eth2 30  vrf3 10.0.30.1/24 2001:db8:0:30::1/64
R2 eth2 30  vrf3 10.0.30.1/24 2001:db8:0:30::1/64
EOF

        template frr-bgpd.Rx.conf frr-bgpd.$uts.conf digit=${uts#R}
        service frr
        ;;
    H1|H2)
        ip addr add 10.0.${uts#H}0.10/24 dev eth0
        ip addr add 2001:db8:0:${uts#H}0::100/64 dev eth0
        ip route add default via 10.0.${uts#H}0.1
        ip route add default via 2001:db8:0:${uts#H}0::1
        ;;
    H3|H4)
        ip addr add 10.0.30.${uts#H}0/24 dev eth0
        ip addr add 2001:db8:0:30::${uts#H}00/64 dev eth0
        ip route add default via 10.0.30.1
        ip route add default via 2001:db8:0:30::1
        ;;
esac
