#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

if onhost; then
    for R in 1 2 3 4 5; do
        uts=r$R template cisco-rX.conf.j2 cisco-r$R.conf
    done
fi

spawn cisco-iosxrv r1 networks r1r2,r1r5,r1r6
spawn cisco-iosxrv r2 networks r1r2,r2r3
spawn cisco-iosxrv r3 networks r2r3,r3r4,r3r7
spawn cisco-iosxrv r4 networks r3r4,r4r5
spawn cisco-iosxrv r5 networks r4r5,r1r5
spawn vm ce6 network r1r6
spawn vm ce7 network r3r7

run

case $uts in
    ce*)
        template run-ceX.j2 run.$uts
        sh run.$uts
        template bird.ceX.conf.j2 bird.$uts.conf
        service bird
        ;;
esac
