#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

for disk in vda~ vdb~ vdc~ vdd~; do
    QEMU_ARGS="${QEMU_ARGS+ }$QEMU_ARGS -drive file=$PWD/$disk,if=virtio,media=disk,format=raw"
    [ ! -f $disk ] || continue
    dd if=/dev/zero bs=1M seek=100 count=1 of=$disk
done

spawn vm host network oob

run

mount -t tmpfs tmpfs /etc/lvm

# This is not very reliable since we may race with the kernel.
mdadm --stop --scan || true
mdadm --assemble --scan || true
