#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

for disk in vda~ vdb~ vdc~ vdd~; do
    QEMU_ARGS="${QEMU_ARGS+ }$QEMU_ARGS -drive file=$PWD/$disk,if=virtio,media=disk,format=raw"
    [ ! -f $disk ] || continue
    dd if=/dev/zero of=$disk bs=1M count=10
done

spawn vm host network oob

run
