#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

# Which VM to spawn
spawn vm R1 network 1,2
spawn vm R2 network 1,2

run

# Executed on each VM
ip link add name lag1 type bond
ip link set down dev eth0
ip link set down dev eth1
ethtool -s eth0 speed 10000 duplex full
ethtool -s eth1 speed 10000 duplex full
>/sys/class/net/lag1/bonding/mode      echo 802.3ad
>/sys/class/net/lag1/bonding/lacp_rate echo fast
>/sys/class/net/lag1/bonding/miimon    echo 100
>/sys/class/net/lag1/bonding/min_links echo 1
>/sys/class/net/lag1/bonding/xmit_hash_policy echo layer3+4
>/sys/class/net/lag1/bonding/slaves    echo +eth1
>/sys/class/net/lag1/bonding/slaves    echo +eth0
ip link set up dev lag1
ip link set up dev eth0
ip link set up dev eth1

ip addr add 203.0.113.${uts#R}/29 dev lag1

case $uts in
    R1) lldpd ;;
    R2)
        ip maddr add 01:80:c2:00:00:0e dev lag1
        ip maddr add 01:80:c2:00:00:0e dev eth0
        ip maddr add 01:80:c2:00:00:0e dev eth1
        # User is expected to run ./capture here
esac
