#!/bin/sh

LABNAME="6rd"

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

spawn vm CE network 1           # client
spawn vm R1 networks 1,2        # first-hop
spawn vm R2 networks 2,3        # second-hop
spawn vm R3 networks 3,4        # third-hop
spawn vm R4 networks 4,6,7      # border dual stack router
spawn vm BR1 networks 6         # first 6rd gateway
spawn vm BR2 networks 6         # second 6rd gateway
spawn vm internet network 7     # "internet"

run

# <-------- IPv4 --------><-- IPv4/IPv6 -->
# CE -- R1 -- R2 -- R3 -- R4 -- internet
#                         |
#                         |-- BR1
#                         \-- BR2

case $uts in
    CE)
        ip addr add 198.51.100.234/24 dev eth0
        ip route add default via 198.51.100.1 dev eth0
        ;;
    R1)
        ip addr add 198.51.100.1/24 dev eth0
        ip addr add 203.0.113.1/30 dev eth1
        sysctl -qw net.ipv4.ip_forward=1
        service bird            # OSPF
        ;;
    R2)
        ip addr add 203.0.113.2/30 dev eth0
        ip addr add 203.0.113.5/30 dev eth1
        sysctl -qw net.ipv4.ip_forward=1
        service bird            # OSPF
        ;;
    R3)
        ip addr add 203.0.113.6/30 dev eth0
        ip addr add 203.0.113.9/30 dev eth1
        sysctl -qw net.ipv4.ip_forward=1
        service bird            # OSPF
        ;;
    R4)
        ip addr add 203.0.113.10/30 dev eth0
        ip addr add 203.0.113.17/29 dev eth1
        ip addr add 203.0.113.33/30 dev eth2
        ip -6 addr add 2001:db8:6::4/120 dev eth1
        ip -6 addr add 2001:db8:7::4/120 dev eth2
        sysctl -qw net.ipv4.ip_forward=1
        sysctl -qw net.ipv6.conf.all.forwarding=1
        service bird          # OSPF + eBGP (internet) + iBGP (6rd HA)
        ;;
    BR1)
        ip addr add 203.0.113.18/29 dev eth0
        ip -6 addr add 2001:db8:6::11/120 dev eth0
        ip route add default via 203.0.113.17
        ip -6 route add default via 2001:db8:6::4
        ;;
    BR2)
        ip addr add 203.0.113.19/29 dev eth0
        ip -6 addr add 2001:db8:6::12/120 dev eth0
        ip route add default via 203.0.113.17
        ip -6 route add default via 2001:db8:6::4
        ;;
    internet)
        ip addr add 203.0.113.34/30 dev eth0
        ip -6 addr add 2001:db8:7::7/120 dev eth0
        ip addr add 8.8.8.8/32 dev dummy0
        ip -6 addr add 2001:4860:4860::8888/128 dev dummy0
        sysctl -qw net.ipv4.ip_forward=1
        sysctl -qw net.ipv6.conf.all.forwarding=1
        service bird            # eBGP
        ;;
esac

# 6RD configuration
sixrd_br=203.0.113.254
sixrd_mtu=1480
sixrd_ttl=64
sixrd_prefix=2001:db9::/32
case $uts in
        CE)
                ipv4=$(ifdata -pa eth0)
                ipv6_prefix=$(printf "%s:%02x%02x:%02x%02x" ${sixrd_prefix%::*} $(echo $ipv4 | tr . ' '))::
                ipv6_prefixlen=64
                ipv6=${ipv6_prefix}1
                ip tunnel add 6rd mode sit local $ipv4 ttl $sixrd_ttl
                ip tunnel 6rd dev 6rd 6rd-prefix $sixrd_prefix
                ip link set 6rd mtu $sixrd_mtu
                ip link set up dev 6rd
                ip -6 addr add $ipv6/128 dev 6rd
                ip -6 route add default via ::$sixrd_br dev 6rd

                ip6tables -t mangle -A POSTROUTING -o 6rd \
                          -p tcp --tcp-flags SYN,RST SYN \
                          -j TCPMSS --clamp-mss-to-pmtu
        ;;
        BR*)
                ipv6_prefix=$(printf "%s:%02x%02x:%02x%02x" ${sixrd_prefix%::*} $(echo $sixrd_br | tr . ' '))::
                ip tunnel add 6rd mode sit local $sixrd_br remote any ttl $sixrd_ttl
                ip tunnel 6rd dev 6rd 6rd-prefix $sixrd_prefix
                ip link set 6rd mtu $sixrd_mtu
                ip link set up dev 6rd
                ip -6 addr add $ipv6_prefix/32 dev 6rd

                # TODO: Secure the setup.  Currently, anybody can use
                # this 6rd gateway.  Be sure to restrict its use with
                # some iptables rules.

                sysctl -qw net.ipv4.ip_forward=1
                sysctl -qw net.ipv6.conf.all.forwarding=1
                ip addr add $sixrd_br/32 dev dummy0
                service bird            # iBGP
        ;;
esac

service nginx
