#!/bin/sh

LABNAME="iou"
DEPS="bird"

set -e

ESC="$(printf '\033')"
NORMAL="${ESC}[0m"
RED="${ESC}[31;1m"
GREEN="${ESC}[32;1m"
YELLOW="${ESC}[33;1m"
BLUE="${ESC}[34;1m"
BEGINNING="$(printf '\015\033')[K"

log_begin_msg () {
    printf "${BEGINNING}"
    printf "${BLUE}[…]${NORMAL} $1${BLUE}...${NORMAL} "
}
log_ok_msg () {
    printf "${BEGINNING}"
    echo "$BOLD$GREEN[✔]$NORMAL $1."
}
log_warn_msg () {
    printf "${BEGINNING}"
    echo "$BOLD$YELLOW[⚡]$NORMAL $1!"
}
log_error_msg () {
    printf "${BEGINNING}"
    echo "$BOLD$RED[✘]$NORMAL $1!"
    exit 1
}
log_info_msg () {
    printf "${BEGINNING}"
    echo "$BOLD$BLUE[∗]$NORMAL $1."
}

check_kernel() {
    log_begin_msg "Checking kernel version"
    [ -f "$KERNEL" ] || log_error_msg "Unable to find kernel $KERNEL"
    VERSION=$(file "$KERNEL" | sed -n 's/.*: Linux kernel x86 boot executable bzImage, version \([^ ]*\) .*/\1/p')
    [ -n "$VERSION" ] || log_error_msg "Unable to determine version for $KERNEL"
    log_ok_msg "Found kernel $VERSION"

    log_begin_msg "Check kernel configuration"
    CONFIG="$(dirname $KERNEL)/config-$VERSION"
    [ -f "$CONFIG" ] || log_error_msg "Unable to find configuration file $CONFIG"
    cat <<EOF | while read el; do
9P_FS=[ym]
NET_9P=[ym]
NET_9P_VIRTIO=[ym]
VIRTIO=[ym]
VIRTIO_PCI=[ym]
SERIAL_8250=y
SERIAL_8250_CONSOLE=y
TMPFS=y
BLK_DEV_INITRD=y
DEVTMPFS=[ym]
EOF
        grep -qx "CONFIG_$el" $CONFIG || log_error_msg "Kernel not configured with CONFIG_$el"
    done

    if grep -Eqc "CONFIG_OVERLAYFS_FS=[ym]" $CONFIG; then
        log_ok_msg "Kernel configuration checked. overlayfs present"
        UNION="${UNION}${UNION+ }overlayfs"
    elif grep -Eqc "CONFIG_OVERLAY_FS=[ym]" $CONFIG; then
        log_ok_msg "Kernel configuration checked. overlayfs present"
        UNION="${UNION}${UNION+ }overlay"
    fi
    if grep -qc "CONFIG_AUFS_FS=[ym]" $CONFIG; then
        log_ok_msg "Kernel configuration checked. AUFS present"
        UNION="${UNION}${UNION+ }aufs"
    fi
    [ -n "$UNION" ] || \
        log_error_msg "Kernel configuration checked. Neither overlayfs nor AUFS present"

    log_begin_msg "Search for modules"
    for dir in "$(dirname $KERNEL)/lib/modules/$VERSION" "/lib/modules/$VERSION"; do
        [ -d $dir ] || continue
        MODULES="$dir"
        break
    done
    if [ -z "$MODULES" ]; then
        log_warn_msg "Unable to find module directory"
    else
        log_ok_msg "Modules are in $MODULES"
    fi
}

check_dependencies() {
    log_begin_msg "Checking if dependencies are present"
    for exec in \
        busybox \
        qemu-system-x86_64 \
        tmux \
        expect \
        vde_switch \
        start-stop-daemon \
        $DEPS; do
        which $exec 2> /dev/null > /dev/null || log_error_msg "$exec is not installed"
    done
    log_ok_msg "All dependencies are met"
}

setup_tmp () {
    TMP=$(mktemp -d)
    trap "ret=$? ; cleanup" EXIT
    log_info_msg "TMP is $TMP"
}

# Run our lab in tmux
setup_screen() {
    if [ -z "$TMUX" ] || [ x"$(tmux list-panes -F '#{session_name}')" != x"$LABNAME" ]; then
        unset TMUX
        exec tmux new-session -s "$LABNAME" -n main \
            "env ROOT=$ROOT VERSION=$VERSION LINUX=$LINUX $PROGNAME $PROGARGS || read"
    fi
    sleep 1
    tmux set-option -q prefix C-b
    tmux set-option -q set-remain-on-exit on
    tmux bind-key r respawn-window
}

# Setup a VDE switch
setup_switch() {
    log_begin_msg "Setup switch $1"
    cat <<EOF > "$TMP/switch-$1.conf"
plugin/add /usr/lib/vde2/plugins/pdump.so
pdump/filename $TMP/switch-$1.pcap
pdump/buffered 0
pdump/active 1
EOF
    start-stop-daemon -b --no-close --make-pidfile --pidfile "$TMP/switch-$1.pid" \
        --start --startas $(which vde_switch) -- \
        --sock "$TMP/switch-$1.sock" --mgmt "$TMP/switch-management-$1.sock" \
        --rcfile "$TMP/switch-$1.conf"
    # Management socket can be used with:
    #    socat - UNIX-CONNECT:"$TMP/switch-management-$1.sock"

    log_ok_msg "Switch $1 started"
}

setup_initrd () {
    log_begin_msg "Build initrd"
    DESTDIR=$TMP/initrd
    mkdir -p $DESTDIR

    # Copy busybox and eventually insmod
    bins="busybox"
    busybox --list | grep -qFx insmod || bins="$bins insmod"
    for bin in $bins; do
        install -D "$(which $bin)" ${DESTDIR}/bin/$bin
        for x in $(ldd "$(which $bin)" 2> /dev/null | sed -e '
               /\//!d;
               /linux-gate/d;
               /=>/ {s/.*=>[[:blank:]]*\([^[:blank:]]*\).*/\1/};
               s/[[:blank:]]*\([^[:blank:]]*\) (.*)/\1/' 2>/dev/null); do
            [ -f "${DESTDIR}/$x" ] || install -D "$x" "${DESTDIR}/$x"
        done
    done

    # Configure busybox
    for applet in $(${DESTDIR}/bin/busybox --list); do
        ln -s busybox ${DESTDIR}/bin/${applet}
    done

    # Add modules
    [ -z "$MODULES" ] || {
        modules="9pnet_virtio 9p virtio_pci $UNION"
        for mod in $modules; do
            modprobe --all --set-version="${VERSION}" -d ${MODULES}/../../.. \
                --ignore-install --quiet --show-depends $mod > /dev/null || {
                log_warn_msg "Unable to find module $mod"
                log_begin_msg "Continue building initrd"
            }
            modprobe --all --set-version="${VERSION}" -d ${MODULES}/../../.. \
                --ignore-install --quiet --show-depends $mod |
            while read prefix kmod options ; do
                [ "${prefix}" = "insmod" ] || continue
                grep -qFw "$kmod" ${DESTDIR}/modules 2> /dev/null || {
                    install -D "$kmod" "${DESTDIR}/${kmod}"
                    echo $prefix $kmod $options >> ${DESTDIR}/modules
                }
            done
        done
    }

    # Copy this program
    cp "$PROGNAME" ${DESTDIR}/init

    # Create /tmp
    mkdir ${DESTDIR}/tmp

    # Build initrd
    (cd "${DESTDIR}" && find . | cpio --quiet -R 0:0 -o -H newc | gzip > $TMP/initrd.gz)

    log_ok_msg "initrd built in $TMP/initrd.gz"
}

random_mac () {
    name=$1
    net=$2
    mac=$(echo $name-$net | sha1sum | \
        awk '{print "52:54:" substr($1,0,2) ":" substr($1, 2, 2) ":" substr($1, 4, 2) ":" substr($1, 6, 2)}')
    echo $mac $name >> $TMP/dnsmasq.leases
    echo $mac
}

start_vm () {
    name=$1
    shift

    netargs=""
    saveifs="$IFS"
    IFS=,
    for net in $NET; do
        mac=$(random_mac $name $net)
        netargs="$netargs -net nic,model=virtio,macaddr=$mac,vlan=$net"
        netargs="$netargs -net vde,sock=$TMP/switch-$net.sock,vlan=$net"
    done
    IFS="$saveifs"

    log_info_msg "Start VM $name"
    # /root is mounted with version 9p2000.u to allow access to /dev,
    # /sys and to mount new partitions over them. This is not the case
    # for 9p2000.L.
    cat <<EOF > "$TMP/vm-$name.exec"
#!/bin/sh
        echo
        exec start-stop-daemon --make-pidfile --pidfile "$TMP/vm-$name.pid" \
        --start --startas $(which qemu-system-x86_64) -- \
        -enable-kvm \
        -nodefconfig -nodefaults \
        -display none \
        \
        -chardev stdio,id=charserial0,signal=off \
        -device isa-serial,chardev=charserial0,id=serial0 \
        -chardev socket,id=charserial1,path=$TMP/vm-$name-serial.pipe,server,nowait \
        -device isa-serial,chardev=charserial1,id=serial1 \
        \
        -chardev socket,id=con0,path=$TMP/vm-$name-console.pipe,server,nowait \
        -mon chardev=con0,mode=readline,default \
        \
        -fsdev local,security_model=passthrough,id=fsdev-root,path=${ROOT} \
        -device virtio-9p-pci,id=fs-root,fsdev=fsdev-root,mount_tag=rootshare \
        -fsdev local,security_model=none,id=fsdev-home,path=${HOME} \
        -device virtio-9p-pci,id=fs-home,fsdev=fsdev-home,mount_tag=homeshare \
        -fsdev local,security_model=none,id=fsdev-lab,path=${PWD} \
        -device virtio-9p-pci,id=fs-lab,fsdev=fsdev-lab,mount_tag=labshare \
        -fsdev local,security_model=none,id=fsdev-tmp,path=${TMP} \
        -device virtio-9p-pci,id=fs-tmp,fsdev=fsdev-tmp,mount_tag=tmpshare \
        -fsdev local,security_model=none,id=fsdev-modules,path=${MODULES}/..,readonly \
        -device virtio-9p-pci,id=fs-modules,fsdev=fsdev-modules,mount_tag=moduleshare \
        \
        -gdb unix:$TMP/vm-$name-gdb.pipe,server,nowait \
        -kernel $KERNEL \
        -no-reboot \
        -initrd $TMP/initrd.gz \
        -append "uts=$name console=ttyS0 panic=1 TERM=$TERM quiet" \
        $netargs \
        $@
EOF
    log_info_msg "GDB server listening on $TMP/vm-$name-gdb.pipe"
    log_info_msg "monitor listening on    $TMP/vm-$name-console.pipe"
    log_info_msg "ttyS1 listening on      $TMP/vm-$name-serial.pipe"
    chmod +x "$TMP/vm-$name.exec"
    tmux new-window -n $name "$TMP/vm-$name.exec"
    tmux select-window -t 1
}

next_port () {
    net=$1
    mkdir -p "$TMP/iou-vde"
    if [ -f "$TMP/iou-vde/$1" ]; then
        current=$(cat "$TMP/iou-vde/$1")
        current=$(( $current + 1 ))
    else
        current=0
    fi
    echo $current > "$TMP/iou-vde/$1"
    echo $current
}

start_iou () {
    name=$1
    instance=$2
    shift

    log_info_msg "Start IOU $name"

    # Netmap file
    saveifs="$IFS"
    i=0
    IFS=,
    for net in $NET; do
        port=$(next_port $net)
        echo $instance:0/$i 666:$net/$port 1 >> "$TMP/NETMAP"
        i=$(($i + 1))
    done
    IFS="$saveifs"

    # Start instance
    ln -s "$PWD/$name.conf" "$TMP"
    cat <<EOF > "$TMP/vm-$name.exec"
#!$(which expect) -f

cd $TMP
spawn $PWD/../images/i86bi-linux-l3.bin -c $name.conf -e 8 -s 0 $instance
set pidfile [open "$TMP/iou-$name.pid" w]
puts \$pidfile [exp_pid]
close \$pidfile
set timeout 120
expect {
  "Would you like to enter the initial configuration dialog?" { send "no\r" }
  timeout { interact }
}
set timeout 5
expect {
  "Would you like to terminate autoinstall?" { send "yes\r" }
  timeout { interact }
}
interact
EOF
    chmod +x "$TMP/vm-$name.exec"
    tmux new-window -n $name "$TMP/vm-$name.exec"
    tmux select-window -t 1
}

start_iou2vde () {
    args=""
    IFS=,
    for net in $NET; do
        args="$args $net:$TMP/switch-$net.sock"
    done
    start-stop-daemon --background --no-close --make-pidfile --pidfile $TMP/iou-vde.pid \
                      --start --startas $PWD/iou2vde.py -- \
                      $args --netmap "$TMP/NETMAP"
}

display_help() {
    cat <<EOF

Some tmux commands (assuming default keybindings) :
 C-b d     - Detach the lab (resume with "tmux attach -t $LABNAME")
 C-b w     - Select a window
 C-b n     - Next window
 C-b p     - Previous window
 C-b l     - Last window
 C-b ?     - Get help
EOF
    echo "Press enter to exit the lab"
    read a
    done=1
}


cleanup() {
    set +e
    [ x"$done" = x"1" ] || {
        printf "${BEGINNING}"
        echo "$BOLD$RED[✘]$NORMAL Got a fatal error. Press enter to terminate everything!"
        read a
    }
    for pid in $TMP/*.pid; do
        kill -15 -$(cat $pid) 2> /dev/null || true
        kill -15 $(cat $pid) 2> /dev/null || true
    done
    sleep 1
    for pid in $TMP/*.pid; do
        kill -9 -$(cat $pid) 2> /dev/null || true
        kill -9 $(cat $pid) 2> /dev/null || true
    done
    rm -rf $TMP
    tmux kill-session -t $LABNAME
}

start_bird() {
    log_begin_msg "Running bird"
    [ -d /run/bird ] || mkdir -p /run/bird
    bird -c /lab/bird.$uts.conf
    log_ok_msg "bird started"
}

# FSM
export STATE=${STATE:-BEGIN}
case $$,$STATE in
    1,BEGIN)
        # In initrd
        log_info_msg "initrd started"
        hostname ${uts}
        export PATH=/usr/local/bin:/usr/bin:/bin:/sbin:/usr/local/sbin:/usr/sbin
        export HOME=/root

        [ ! -f /modules ] || {
            log_info_msg "Loading modules"
            . /modules
        }

        log_begin_msg "Setup root file system"
        mount -n -t tmpfs tmpfs /tmp -o rw
        mkdir /tmp/target
        mkdir /tmp/target/ro
        mkdir /tmp/target/overlay
        mount -n -t 9p    rootshare /tmp/target/ro      -o trans=virtio,version=9p2000.u,ro
        mkdir /tmp/target/rw
        mount -n -t tmpfs tmpfs     /tmp/target/rw      -o rw
        mkdir /tmp/target/rw/workdir
        mkdir /tmp/target/rw/upperdir
        mount -n -t aufs aufs /tmp/target/overlay \
              -o noxino,noatime,dirs=/tmp/target/rw/upperdir:/tmp/target/ro=ro \
              2> /dev/null || \
            mount -n -t overlayfs overlayfs /tmp/target/overlay \
                  -o lowerdir=/tmp/target/ro,upperdir=/tmp/target/rw/upperdir,noatime \
                  2> /dev/null || \
            mount -n -t overlay overlayfs /tmp/target/overlay \
                  -o lowerdir=/tmp/target/ro,upperdir=/tmp/target/rw/upperdir,workdir=/tmp/target/rw/workdir,noatime \
                  2> /dev/null ||
            log_error_msg "Unable to mount AUFS/overlayfs"
        mount -n -t proc  proc /tmp/target/overlay/proc
        mount -n -t sysfs sys  /tmp/target/overlay/sys
        log_ok_msg "Root file system setup"

        log_begin_msg "Clean /tmp and /run"
        for fs in /run /var/run /var/tmp /var/log /tmp; do
            if [ -d /tmp/target/overlay$fs ] && [ ! -h /tmp/target/overlay$fs ]; then
                mount -t tmpfs tmpfs /tmp/target/overlay$fs -o rw,nosuid,nodev
            fi
        done
        log_ok_msg "/tmp, /run and others are clean"

        log_begin_msg "Mount /root"
        mount -t 9p homeshare /tmp/target/overlay/root -o trans=virtio,version=9p2000.L,access=any,rw || \
            log_error_msg "Unable to mount /root"
        log_ok_msg "/root mounted"
        log_begin_msg "Mount /lib/modules"
        mount -t 9p moduleshare /tmp/target/overlay/lib/modules -o trans=virtio,version=9p2000.L,access=0,ro || \
            log_error_msg "Unable to mount /lib/modules"
        log_ok_msg "/root and /lib/modules mounted"

        log_begin_msg "Mount /lab"
        mkdir /tmp/target/overlay/lab
        mount -t 9p labshare /tmp/target/overlay/lab -o trans=virtio,version=9p2000.L,access=any,rw || \
            log_error_msg "Unable to mount /lab"
        log_ok_msg "/lab mounted"

        log_begin_msg "Mount /tmp/lab"
        mkdir /tmp/target/overlay/tmp/lab
        mount -t 9p tmpshare /tmp/target/overlay/tmp/lab -o trans=virtio,version=9p2000.L,access=any,rw || \
            log_error_msg "Unable to mount /tmp/lab"
        log_ok_msg "/tmp/lab mounted"

        log_info_msg "Change root"
        export STATE=CHROOTED
        exec chroot /tmp/target/overlay /lab/setup
        ;;

    1,CHROOTED)
        log_begin_msg "Starting udev"
        udev_log=err
        rm -f /etc/udev/rules.d/70-persistent-net.rules
        mount -n -o size=10M,mode=0755 -t devtmpfs devtmpfs /dev
        udevadm info --cleanup-db
        udevd --daemon
        udevadm trigger --action=add
        udevadm settle
        log_ok_msg "udev started"

        sleep 1
        log_info_msg "Setup interfaces"
        modprobe dummy 2 >/dev/null || true
        for intf in /sys/class/net/*; do
            intf=$(basename $intf)
            ip a l dev $intf 2> /dev/null >/dev/null || continue
            case $intf in
                lo|eth*|dummy*)
                    ip link set up dev $intf
                    ;;
            esac
        done

        log_info_msg "Start syslog"
        rsyslogd

        log_info_msg "Setup terminal"
        export STATE=GETTY
        exec setsid /sbin/agetty -L ttyS0 -a root -l /lab/setup -i 115200 $TERM
        ;;

    1,GETTY)
        log_begin_msg "Setup terminal size"
        # We are guaranteed to be in a tmux session, so we will get an
        # answer to the escape code we send. Otherwise, we may just
        # block!
        stty -echo
        stty raw
        printf '[18t'
        width=
        height=
        p=0
        while true; do
            char="$(timeout --foreground 1s dd bs=1 count=1 2> /dev/null || true)"
            case "$p,$char" in
                "0,;")
                    # End of CSI
                    p=1
                    ;;
                "1,;")
                    # End of height
                    stty rows $height
                    p=2
                    ;;
                "1,"*)
                    height="$height$char"
                    ;;
                "2,t"|"2,")
                    # End of width
                    stty columns $width
                    p=3
                    ;;
                "2,"*)
                    width="$width$char"
                    ;;
            esac
            [ x"$p" != x"3" ] || break
        done
        stty -raw
        stty echo
        log_ok_msg "Terminal size is $(tput cols)x$(tput lines)"

        export STATE=SETUP
        . /lab/setup

        log_begin_msg "Setup additional commands"
        mkdir /tmp/tools
        export PATH=$PATH:/tmp/tools
        rm -f /sbin/reboot /sbin/halt
        cat <<EOF > /sbin/reboot
#!/bin/sh
echo b > /proc/sysrq-trigger
EOF
        cat <<EOF > /sbin/halt
#!/bin/sh
echo b > /proc/sysrq-trigger
EOF
        chmod +x /sbin/reboot /sbin/halt
        log_ok_msg "System can be halted with halt or reboot"

        while true; do
            log_info_msg "Spawning a shell"
            cd $HOME
            export SSH_TTY=$(tty)
            if [ -f $HOME/.zshrc ]; then
                /bin/zsh -i
            else
                /bin/bash -i
            fi || sleep 1
        done
        ;;

    *,SETUP)
        log_info_msg "Setup IP addresses"
        case $uts in
            R1)
                ip addr add 192.0.2.1/24 dev eth0
                ip addr add 198.51.100.101/32 dev dummy0
                start_bird
                ;;
            R2)
                ip addr add 192.0.2.2/24 dev eth0
                ip addr add 198.51.100.102/32 dev dummy0
                start_bird
                ;;
        esac
        ;;

    *,BEGIN)
        # Initial state
        [ $(id -u) != 0 ] || {
            log_error_msg "You should not run this as root"
            exit 1
        }
        PROGNAME="$(readlink -f "$0")"
        ROOT="$(readlink -f "${ROOT:-/}")" # Root filesystem
        KERNEL="$(readlink -f "${1:-/boot/vmlinuz-$(uname -r)}")" # Kernel
        [ $# -lt 1 ] || shift

        check_kernel
        check_dependencies
        setup_screen
        setup_tmp
        setup_initrd

        setup_switch 1
        sleep 0.5

        NET=1     start_vm  R1
        NET=1     start_vm  R2
        NET=1     start_iou IOU1 10
        NET=1     start_iou IOU2 11
        NET=1     start_iou2vde

        display_help
        ;;
esac

# Local Variables:
# mode: sh
# indent-tabs-mode: nil
# sh-basic-offset: 4
# End:
