#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

spawn juniper-vqfx QFX1 networks 1,3
spawn juniper-vqfx QFX2 networks 2,3
spawn vm H1 networks 1,2

run

case $uts in
    H1)
        modprobe bonding
        ethtool -s eth0 speed 1000 duplex full
        ethtool -s eth1 speed 1000 duplex full
        ip link add name bond0 type bond
        echo 802.3ad > /sys/class/net/bond0/bonding/mode
        echo 100 > /sys/class/net/bond0/bonding/miimon
        echo 1 > /sys/class/net/bond0/bonding/lacp_rate
        echo layer3+4 > /sys/class/net/bond0/bonding/xmit_hash_policy
        ip link set down dev eth0
        ip link set down dev eth1
        ip link set master bond0 dev eth0
        ip link set master bond0 dev eth1
        ip link set up dev bond0
        ip link set up dev eth0
        ip link set up dev eth1

        for vlan in 7 8 9 10 11 12 13 14 15; do
            ip link add name bond0.${vlan} link bond0 type vlan id ${vlan}
            ip link set up dev bond0.${vlan}
            ip addr add 172.27.${vlan}.10/24 dev bond0.${vlan}
            # This doesn't help
            # ip neigh replace 172.27.${vlan}.1 lladdr 16:50:15:00:02:${vlan} dev bond0.${vlan}
        done

        service bird
        ;;
esac
