#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

spawn juniper-vqfx QFX network 1,2,3
spawn vm R1 network 1,2
spawn vm R2 network 1,3

run

case $uts in
    R1)
        ip addr add 2001:db8::1/64 dev eth0      # On VDE switch
        ip addr add 2001:db8:aaaa::1/64 dev eth1 # On QFX switch
        ip addr add 2001:db8:c0ff::42/128 dev dummy0
        ;;
    R2)
        ip addr add 2001:db8::2/64 dev eth0      # On VDE switch
        ip addr add 2001:db8:aaaa::2/64 dev eth1 # On QFX switch
        ip addr add 2001:db8:dead::200/128 dev dummy0
        ;;
esac
service bird
