#!/bin/sh

cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

# Which VM to spawn
spawn vm          S1  networks 1,2,3,4
spawn juniper-vrr R   networks 1,2    # R1 and R2
spawn vm          R3  networks 3      # R3 with GoBGP
spawn vm          R4  networks 4      # R4 with BIRD

run

# Executed on each VM
case $uts in
    S1)
        # Link everyone with everyone. Twice (to get ECMP paths)
        count=$(echo /sys/class/net/eth* | wc -w)
        for v in $(seq $((count * (count - 1) / 2))); do
            for offset in 100 200; do
                vlan=$((v+offset))
                ip link add wire$vlan type bridge
                ip link set up dev wire$vlan
                for iface in $(seq $count); do
                    iface=eth$((iface-1))
                    ip link add name ${iface}.${vlan} link ${iface} type vlan id ${vlan}
                    ip link set up dev ${iface}.${vlan}
                    ip link set master wire${vlan} ${iface}.${vlan}
                done
            done
        done

        cat <<EOF > /tmp/tools/ddos
#!/bin/sh
case "\${1:-all}" in
    wire*)
        ebtables -A FORWARD --logical-in \$1 -p IPv6 --ip6-proto udp --ip6-destination-port 3784 -j DROP
        ebtables -A FORWARD --logical-in \$1 -p IPv6 --ip6-proto udp --ip6-source-port 3784 -j DROP
        ebtables -A FORWARD --logical-in \$1 -p IPv6 --ip6-proto tcp --ip6-destination-port 179 -j DROP
        ebtables -A FORWARD --logical-in \$1 -p IPv6 --ip6-proto tcp --ip6-source-port 179 -j DROP
        ebtables -A FORWARD --logical-in \$1 -p IPv6 --ip6-proto ipv6-icmp --limit 5/s -j ACCEPT
        ebtables -A FORWARD --logical-in \$1 -p IPv6 --ip6-proto ipv6-icmp -j DROP
        ;;
    all)
        ebtables -A FORWARD -p IPv6 --ip6-proto udp --ip6-destination-port 3784 -j DROP
        ebtables -A FORWARD -p IPv6 --ip6-proto udp --ip6-source-port 3784 -j DROP
        ebtables -A FORWARD -p IPv6 --ip6-proto tcp --ip6-destination-port 179 -j DROP
        ebtables -A FORWARD -p IPv6 --ip6-proto tcp --ip6-source-port 179 -j DROP
        ebtables -A FORWARD -p IPv6 --ip6-proto ipv6-icmp --limit 5/s -j ACCEPT
        ebtables -A FORWARD -p IPv6 --ip6-proto ipv6-icmp -j DROP
        ;;
    off)
        ebtables -F FORWARD
        ;;
esac
EOF
        chmod +x /tmp/tools/ddos
        ;;
    R3)
        # GoBGP
        ip addr add 2001:db8:10::3/128 dev lo
        for v in 102 202 103 203 106 206; do
            ip link add name eth0.$v link eth0 type vlan id $v
            ip link set up dev eth0.$v
            ip addr add 2001:db8:${v}::3/120 dev eth0.${v}
        done
        service gobgp
        sleep 1
        gobgp global rib add 2001:db8:10::3/128 origin igp -a ipv6
        ;;
    R4)
        # BIRD
        ip addr add 2001:db8:10::4/128 dev lo
        for v in 104 204 105 205 106 206; do
            ip link add name eth0.$v link eth0 type vlan id $v
            ip link set up dev eth0.$v
            ip addr add 2001:db8:${v}::4/120 dev eth0.${v}
        done
        service bird
        ;;
esac
